name: Terraform CI/CD Pipeline

on:
  # push:
  #   branches:
  #     - main

  # pull_request:
  #   branches:
  #     - main

  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  IMAGE_NAME: shopflow

jobs:

  # test:
  #   name: Lint and Unit Tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.11"

  #     - name: Install Dependencies
  #       run: |
  #         pip install -r requirements.txt
  #         pip install pytest flake8

  #     - name: Run Lint
  #       run: flake8 .

  #     - name: Run Unit Tests
  #       run: pytest

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    # needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        # Use today's UTC date plus the GitHub run ID.
        # This keeps the tag easy to explain and still unique for the run.
        id: image-tag
        run: |
          TODAY="$(date -u +%Y-%m-%d)"
          IMAGE_TAG="${TODAY}-${GITHUB_RUN_ID}"
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: Build Docker Image
        run: |
          docker build -t "${IMAGE_NAME}:${{ steps.image-tag.outputs.image_tag }}"  .

      - name: Tag Docker Image
        run: |
          docker tag $IMAGE_NAME:${{ steps.image-tag.outputs.image_tag }} \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.image_tag }}
          docker tag $IMAGE_NAME:${{ steps.image-tag.outputs.image_tag }} \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker Image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.image_tag }}
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:latest

  terraform-plan:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest
    needs: docker

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan


  terraform-apply:
    name: Terraform Apply and Deploy
    runs-on: ubuntu-latest
    needs: terraform-plan

    environment:
      name: production

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
## just for me to destroy

      - name: sleep
        run: sleep 100
        
      - name: Terraform destroy
        run: terraform destroy -auto-approve


  # smoke-test:
  #   name: Smoke Test
  #   runs-on: ubuntu-latest
  #   needs: terraform-apply

  #   steps:
  #     - name: Test Application
  #       run: |
  #         curl -f http://YOUR-APP-URL || exit 1

  #     - name: Rollback on Failure
  #       if: failure()
  #       run: |
  #         echo "Smoke test failed!"
  #         echo "Starting rollback..."

  #         cd terraform
  #         terraform destroy -auto-approve
